service: chess-scape
frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser
  region: us-east-1
  # apiName: ${self:service}
  # memorySize: : 128 # mb
  # timeout: 0: : 10 # seconds
  environment: ${file(yml/environment.yml)}
  # apiGateway:
  #   binaryMediaTypes:
  #     - '*/*'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*'

plugins:
  # - serverless-webpack
  - serverless-s3-sync
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-s3-local

custom: ${file(yml/variables.yml)}

functions: ${file(yml/functions.yml)}

resources:
  - ${file(yml/dynamo.yml)}
  - ${file(yml/s3.yml)}