Resources:
  ClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.clientsTableName}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: TOKEN
          AttributeType: S
        - AttributeName: connectionID
          AttributeType: S
        - AttributeName: room
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: token-index
          KeySchema:
            - AttributeName: TOKEN
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
        - IndexName: connection-index
          KeySchema:
            - AttributeName: connectionID
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
        - IndexName: room-index
          KeySchema:
            - AttributeName: room
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
  RoomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.roomsTableName}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  MatchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.matchesTableName}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  MediaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.mediaTableName}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: roomID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: room-index
          KeySchema:
            - AttributeName: roomID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  ServiceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.serviceTableName}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST          
  SavedMatchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.savedMatchesTableName}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST          
  SavedChatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.savedChatsTableName}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST          